env:
  node: true
  es2020: true
  es6: true
extends:
  - google
  - 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
parser: 'babel-eslint'
rules:
  {
    'require-jsdoc': 0,
    'arrow-parens': 0,
    'prettier/prettier': 'error',
    'max-len': ['error', { 'code': 100, 'ignoreUrls': true, 'ignoreComments': false }],
    'no-unused-vars': 1,
  }
